### ISSUE TITLE
Video and team picture on front page

### ISSUE THREAD

**Issue by NathanielHorne** [frc1418/frc1418.github.io#209]
The background video and the team photo have both been updated for this year, the paths and JS variables apply to both, but for some reason, they aren't executed. If you look at the video.mp4 and the assets/img/team.jpg files on the code being run by the website are current. Could someone see what's happening?

**Comment by ErikBoesen** [comment]
The reason this is happening is because the files have not been updated as you say. I don't know what you're looking at, but those files were both last updated two years ago and contain the content expected.

By the way, we don't really need to update the background video if you don't want to worry about it. The one we have now is alright.
