### ISSUE TITLE
Add Graduated Members to Alumni Page

### ISSUE THREAD

**Issue by BrandonWerbel** [frc1418/frc1418.github.io#469]
- [x] Anuragi Thapliya
- [x] Andrew Lester
- [x] Joe Carpenter
- [x] Mira Vega
- [x] Kevin Zhang
- [x] Daniel Trauberman
- [x] Cole Tarter
- [x] Sam Klemic
- [x] Rafaela Paquete 
- [x] Sophia Urbom

(Please comment if I forgot someone)

For each of the above, we need to find out where they are currently going to college, find the college's longitude/latitude, and add to info to [js/alumni.js](https://github.com/frc1418/frc1418.github.io/blob/master/js/alumni.js)

If reaching out, we should also ask if they would like to contribute a quote to add to the page.

**Comment by MyaTaheri** [comment]
I found out where Anuragi Thapliya, Andrew Lester, Joe Carpenter, Kevin Zhang, and Cole Tarter went to school and their schools are already on the map.

I couldn't find the schools for Sam Klemic, Mira Vega, Daniel Trauberman, Rafaela Paquete, or Sophia Urbom

**Comment by AndrewLester** [comment]
@MyaTaheri I can help with this one:
- Sam Klemic &rarr; Virginia Tech
- Daniel Trauberman &rarr; Indiana University Bloomington
- Rafaela Paquete &rarr; University of Padua
- Sophia Urbom &rarr; Duke University

The above should be fine to add since they're all [publicly accessible](https://apc-mhs.com/seniormap/).

Since Mira's isn't, I won't send what I remember it was here + it may have changed. I think she's in the slack, so trying a slack DM may be a good place to start?

**Comment by MyaTaheri** [comment]
Thank you so much!  I think all of these schools are already on the map.  I can see if I can message Mira on Slack.

**Comment by ErikBoesen** [comment]
I thiiiink Mira went to VCU? I'm not sure though.
